name: This should not be called
on:
  workflow_dispatch: ~

permissions: read-all

jobs:
  versions:
    name: List monitored action versions
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/attest-build-provenance@v3.0.0
      - uses: actions/cache@v4.3.0
      - uses: gitleaks/gitleaks-action@v2.3.9
