name: actions/attest-build-provenance@v3
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest-build-provenance-v3.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest-build-provenance-v3.yml
  schedule:
    - cron: "24 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             dist/606.index.js dist/index.js
      build-cmd:         npm run bundle
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/attest-build-provenance
      version-ref:       v3
