name: actions/setup-node
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-node.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-node.yml
  schedule:
    - cron: "36 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 24.x
      repository:   actions/setup-node
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6.1.0
