name: actions/dependency-review-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-dependency-review-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-dependency-review-action.yml
  schedule:
    - cron: "13 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/dependency-review-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@v4.8.2
