name: actions/cache
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-cache.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-cache.yml
  schedule:
    - cron: "14 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 24.x
      repository:   actions/cache
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v5
