name: actions/attest
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest.yml
  schedule:
    - cron: "2 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         npm run bundle
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/attest
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/attest@v3.2.0
