name: actions/setup-dotnet
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-setup-dotnet.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-setup-dotnet.yml
  schedule:
    - cron: "6 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 24.x
      repository:   actions/setup-dotnet
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v5.0.1
