name: actions/attest-build-provenance
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-attest-build-provenance.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-attest-build-provenance.yml
  schedule:
    - cron: "24 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:         npm run package
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/attest-build-provenance
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/attest-build-provenance@v3.0.0
