name: actions/create-github-app-token
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-create-github-app-token.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-create-github-app-token.yml
  schedule:
    - cron: "29 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:         npm run build
      install-cmd:       npm clean-install
      node-version-file: package.json
      repository:        actions/create-github-app-token
  version:
    if: ${{ false }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@v2.2.0
