name: actions/stale
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-stale.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/actions-stale.yml
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/stale
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10.1.1
