name: actions/deploy-pages
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-deploy-pages.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-deploy-pages.yml
  schedule:
    - cron: "44 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         npm run prepare
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/deploy-pages
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4.0.5
