name: actions/download-artifact
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-download-artifact.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-download-artifact.yml
  schedule:
    - cron: "34 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 24.x
      repository:   actions/download-artifact
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7.0.0
