name: asdf-vm/actions
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/asdf-vm-actions.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/asdf-vm-actions.yml
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         pnpm build
      install-cmd: |
        PNPM_VERSION=$(jq -r '.engines.pnpm' package.json | sed 's/^=//')

        corepack enable
        corepack prepare "pnpm@${PNPM_VERSION}" --activate

        corepack pnpm install --ignore-scripts
      node-version-file: .tool-versions
      repository:        asdf-vm/actions
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: asdf-vm/actions@v4.0.1
