name: cardinalby/schema-validator-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/cardinalby-schema-validator-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/cardinalby-schema-validator-action.yml
  schedule:
    - cron: "31 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20
      repository:   cardinalby/schema-validator-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/schema-validator-action@3.1.1
