name: docker/setup-buildx-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/docker-setup-buildx-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/docker-setup-buildx-action.yml
  schedule:
    - cron: "38 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    yarn build
      install-cmd:  yarn install
      node-version: 20
      repository:   docker/setup-buildx-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3.12.0
