name: dorny/paths-filter
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/dorny-paths-filter.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/dorny-paths-filter.yml
  schedule:
    - cron: "23 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   dorny/paths-filter
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3.0.2
