name: extractions/setup-crate
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/extractions-setup-crate.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/extractions-setup-crate.yml
  schedule:
    - cron: "9 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20
      repository:   extractions/setup-crate
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-crate@v1.4.0
