name: gitleaks/gitleaks-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gitleaks-gitleaks-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gitleaks-gitleaks-action.yml
  schedule:
    - cron: "3 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:         npx ncc build src/index.js
      install-cmd:       npm clean-install
      node-version-file: .nvmrc
      repository:        gitleaks/gitleaks-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-24.04
    steps:
      - uses: gitleaks/gitleaks-action@v2.3.9
