name: golangci/golangci-lint-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/golangci-golangci-lint-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/golangci-golangci-lint-action.yml
  schedule:
    - cron: "42 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm install
      node-version: 24.x
      repository:   golangci/golangci-lint-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: golangci/golangci-lint-action@v9.2.0
