name: JamesIves/github-pages-deploy-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/jamesives-github-pages-deploy-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/jamesives-github-pages-deploy-action.yml
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         yarn build
      install-cmd:       |
        npm install -g yarn
        yarn install --frozen-lockfile
      node-version-file: .node-version
      repository:        JamesIves/github-pages-deploy-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4.7.6
