name: JS-DevTools/npm-publish
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/js-devtools-npm-publish.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/js-devtools-npm-publish.yml
  schedule:
    - cron: "26 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    pnpm build
      install-cmd:  |
        corepack enable
        corepack prepare pnpm@10.27.0 --activate

        corepack pnpm install
      node-version: 24
      repository:   JS-DevTools/npm-publish
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v4.1.5
