name: ncipollo/release-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/ncipollo-release-action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/ncipollo-release-action.yml
  schedule:
    - cron: "19 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    yarn build
      install-cmd:  yarn install
      node-version: 20
      repository:   ncipollo/release-action
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.4.0
