name: peter-evans/create-pull-request
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/peter-evans-create-pull-request.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test-new.yml
      - .github/workflows/peter-evans-create-pull-request.yml
  schedule:
    - cron: "18 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test-new.yml
    with:
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   peter-evans/create-pull-request
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@v7.0.11
