name: slsa-framework/slsa-github-generator
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/slsa-framework-slsa-github-generator.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/slsa-framework-slsa-github-generator.yml
  schedule:
    - cron: "4 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  actions-delegator-setup-generic:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         make clean package
      install-cmd:       npm clean-install
      node-version:      22
      repository:        slsa-framework/slsa-github-generator
      working-directory: actions/delegator/setup-generic
  github-actions-detect-workflow-js:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:         make clean package
      install-cmd:       npm clean-install
      node-version:      22
      repository:        slsa-framework/slsa-github-generator
      working-directory: .github/actions/detect-workflow-js
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: slsa-framework/slsa-github-generator@v2.1.0
