name: wearerequired/lint-action@v2
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/wearerequired-lint-action-v2.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/wearerequired-lint-action-v2.yml
  schedule:
    - cron: "39 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             dist/index.js
      build-cmd:         npm run build
      install-cmd:       yarn install
      node-version-file: .nvmrc
      repository:        wearerequired/lint-action
      version-ref:       v2
